version: '3.8'

services:
  neo4j:
    image: neo4j:5.9
    container_name: neo4j
    environment:
      - NEO4J_AUTH=/neo4j # Default: neo4j/neo4j
      - NEO4J_dbms_logs_debug_level=INFO
    ports:
      - "7474:7474" # Interface web
      - "7687:7687" # Interface bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: