// Node Keys
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Vaccine) REQUIRE n.product IS NODE KEY;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Date) REQUIRE n.date IS NODE KEY;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Region) REQUIRE n.name IS NODE KEY;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Country) REQUIRE n.code IS NODE KEY;

// Node Properties Must Exist
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Vaccine) REQUIRE n.company IS NOT NULL;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Vaccine) REQUIRE n.vaccine IS NOT NULL;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Country) REQUIRE n.name IS NOT NULL;
